#!/usr/bin/env python3
"""Full pipeline orchestrator: validate → tts → render → open for review.

Usage:
  python pipeline/make_episode.py <episode-slug>

Example:
  python pipeline/make_episode.py 2026-06-14-nico-williams

Stops at human-review step before publish. Never auto-publishes.
Requires:
  - episodes/<slug>/dossier.yaml  (player context)
  - episodes/<slug>/script.json   (generated by football-scout skill + validated)
  - ELEVENLABS_API_KEY env var
"""
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def run(cmd: list[str], label: str) -> None:
    print(f"\n── {label} ──")
    result = subprocess.run(cmd, cwd=REPO)
    if result.returncode != 0:
        print(f"FAILED: {label}")
        sys.exit(result.returncode)
    print(f"OK: {label}")


def main():
    if len(sys.argv) != 2:
        print("usage: python pipeline/make_episode.py <episode-slug>")
        sys.exit(2)

    slug = sys.argv[1]
    episode_dir = REPO / "episodes" / slug
    script_json = episode_dir / "script.json"

    if not script_json.exists():
        print(f"No script.json at {script_json}. Run /make-episode {slug} in Claude first.")
        sys.exit(1)

    # 1. Validate
    run(
        ["python3", ".claude/skills/football-scout/scripts/validate.py", str(script_json)],
        "Validate script.json"
    )

    # 2. TTS
    run(["python3", "pipeline/tts.py", str(script_json)], "ElevenLabs TTS")

    # 3. Render
    run(["python3", "pipeline/render.py", str(script_json)], "Remotion render")

    # 4. Human review gate
    output = episode_dir / "episode.mp4"
    print(f"""
╔══════════════════════════════════════════════════════╗
║  EPISODE READY FOR REVIEW                           ║
║  {str(output):<50} ║
║                                                      ║
║  Watch the mp4. When approved, publish manually     ║
║  via YouTube Studio / TikTok — or run:              ║
║    python pipeline/publish.py {slug:<22} ║
╚══════════════════════════════════════════════════════╝
""")


if __name__ == "__main__":
    main()
